export const SET_LOGGED_IN = "SET_LOGGED_IN";
export const SET_DEVICE_ID = "SET_DEVICE_ID";
export const SET_TRACK_NAME = "SET_TRACK_NAME";
export const SET_ALBUM_NAME = "SET_ALBUM_NAME";
export const SET_ALBUM_IMAGE = "SET_ALBUM_IMAGE";
export const SET_ARTIST_NAME = "SET_ARTIST_NAME";
export const SET_PLAYING = "SET_PLAYING";
export const SET_POSITION = "SET_POSITION";
export const SET_DURATION = "SET_DURATION";
export const SET_ACCESS_TOKEN = "SET_ACCESS_TOKEN";
export const SET_REFRESH_TOKEN = "SET_REFRESH_TOKEN";
export const SET_ACCESS_TOKEN_EXPIRATION_TIME =
  "SET_ACCESS_TOKEN_EXPIRATION_TIME";
